# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import meter_pb2 as meter__pb2


class ShowMeterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListMeters = channel.unary_stream(
                '/getmeter.ShowMeter/ListMeters',
                request_serializer=meter__pb2.ShowMeterRequest.SerializeToString,
                response_deserializer=meter__pb2.MeterUsage.FromString,
                )


class ShowMeterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListMeters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShowMeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListMeters': grpc.unary_stream_rpc_method_handler(
                    servicer.ListMeters,
                    request_deserializer=meter__pb2.ShowMeterRequest.FromString,
                    response_serializer=meter__pb2.MeterUsage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'getmeter.ShowMeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ShowMeter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListMeters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/getmeter.ShowMeter/ListMeters',
            meter__pb2.ShowMeterRequest.SerializeToString,
            meter__pb2.MeterUsage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
